[project]
name = 'Transparent-Charity-Donation-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donation-management]
path = 'contracts/donation-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.expense-verification]
path = 'contracts/expense-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-allocation]
path = 'contracts/project-allocation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
